exclude = [
    ".venv",
    ".git",
    ".pytest_cache",
    ".ruff_cache",
    ".mypy_cache"
]

line-length = 120
indent-width = 4

target-version = "py313"

[lint]
select = ["E4", "E7", "E9", "F", "W"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
