# Generated by Django 5.2.4 on 2025-07-18 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50, verbose_name='English name')),
                ('name_sci', models.CharField(max_length=50, verbose_name='Scientific (latin) name')),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50, unique=True, verbose_name='Xeno-Canto URL')),
                ('recordist', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('sound_type', models.CharField(max_length=100, null=True)),
                ('license', models.CharField(max_length=30, verbose_name='Creative Commons license type')),
                ('audio', models.FileField(unique=True, upload_to='audio')),
                ('species_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.species')),
            ],
        ),
    ]
