# Generated by Django 5.2.4 on 2025-07-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording',
            old_name='species_id',
            new_name='species',
        ),
        migrations.AlterField(
            model_name='recording',
            name='audio',
            field=models.FileField(max_length=255, unique=True, upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Xeno-Canto ID'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_sci',
            field=models.CharField(max_length=50, unique=True, verbose_name='Scientific (latin) name'),
        ),
    ]
