# Generated by Django 5.2.4 on 2025-07-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_species_id_recording_species_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='downloaded',
            field=models.BooleanField(default=False, verbose_name='Audio file downloaded'),
        ),
    ]
