# Generated by Django 5.2.4 on 2025-07-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_recording_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='license_url',
            field=models.CharField(max_length=255, null=True, verbose_name='Creative Commons license info URL'),
        ),
        migrations.AddField(
            model_name='recording',
            name='xc_audio_url',
            field=models.CharField(max_length=255, null=True, verbose_name='Xeno-Canto audio file URL'),
        ),
    ]
