# Generated by Django 5.2.4 on 2025-07-26 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_recording_license_url_recording_xc_audio_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='family',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Taxonomic family'),
        ),
        migrations.AddField(
            model_name='species',
            name='genus',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Taxonomic genus'),
        ),
        migrations.AddField(
            model_name='species',
            name='order',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Taxonomic order'),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.species')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.region')),
            ],
        ),
    ]
