# Generated by Django 5.2.4 on 2025-07-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_region_species_family_species_genus_species_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=9, null=True, verbose_name='eBird species code'),
        ),
    ]
