# Generated by Django 5.2.4 on 2025-07-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_species_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(fields=('species', 'region'), name='unique_species_region'),
        ),
    ]
