# Generated by Django 5.2.4 on 2025-07-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_observation_unique_species_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
