# Generated by Django 5.2.4 on 2025-08-05 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_region_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='parent_region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subregions', to='quiz.region'),
        ),
    ]
