# Generated by Django 5.2.4 on 2025-08-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_quiz_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='name_fi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Finnish name'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='English name'),
        ),
    ]
