# Generated by Django 5.2.4 on 2025-08-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_species_name_fi_alter_species_name_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='region',
            name='name_fi',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
