# Generated by Django 5.2.4 on 2025-08-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_rename_name_region_name_en_region_name_fi'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='type',
            field=models.CharField(choices=[('REG', 'Regular breeder'), ('IRR', 'Irregular breeder'), ('WIN', 'Winter migrant'), ('PAS', 'Passage migrant'), ('VAG', 'Vagrant'), ('ESC', 'Escapee')], default=None, max_length=3, null=True),
        ),
    ]
