# Generated by Django 5.2.4 on 2025-08-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_observation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Localized common name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_fi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Localized common name'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_fi',
            field=models.CharField(max_length=50, null=True, verbose_name='Localized common name'),
        ),
    ]
