# Generated by Django 5.2.4 on 2025-08-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_region_name_species_name_alter_region_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='length',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
