# Generated by Django 5.2.4 on 2025-08-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_answer_is_correct_quiz_length_quiz_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='sound_type',
            field=models.CharField(choices=[('SNG', 'Song'), ('CAL', 'Call'), ('ALR', 'Alarm call'), ('FLG', 'Flight call'), ('BEG', 'Begging call'), ('DUE', 'Duet'), ('ABR', 'Aberrant'), ('IMI', 'Imitation'), ('DRU', 'Drumming'), ('OTH', 'Other')], db_index=True, max_length=3),
        ),
    ]
