# Generated by Django 5.2.4 on 2025-08-23 07:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_alter_recording_sound_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('type', models.CharField(blank=True, choices=[('BGN', 'List of easily recognizable species, used for regional beginner quizzes')], db_index=True, default=None, max_length=3, null=True)),
                ('is_official', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_lists', to=settings.AUTH_USER_MODEL)),
                ('regions', models.ManyToManyField(blank=True, to='quiz.region')),
            ],
        ),
        migrations.CreateModel(
            name='ListSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.species')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_entries', to='quiz.specieslist')),
            ],
        ),
        migrations.AddConstraint(
            model_name='specieslist',
            constraint=models.UniqueConstraint(fields=('created_by', 'name'), name='unique_user_list_name'),
        ),
        migrations.AddConstraint(
            model_name='listspecies',
            constraint=models.UniqueConstraint(fields=('list', 'species'), name='unique_species_per_list'),
        ),
    ]
