# Generated by Django 5.2.4 on 2025-08-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_specieslist_listspecies_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name': 'Species', 'verbose_name_plural': 'Species'},
        ),
    ]
