# Generated by Django 5.2.4 on 2025-08-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_alter_species_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('BGN', 'Beginner / Easy difficulty'), ('NML', 'Normal / default difficulty')], default='NML', max_length=3),
            preserve_default=False,
        ),
    ]
