# Generated by Django 5.2.4 on 2025-08-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_answer',
            field=models.CharField(default='Yellow Wagtail', max_length=50),
            preserve_default=False,
        ),
    ]
