# Generated by Django 5.2.4 on 2025-08-19 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_security_answer'),
        ('quiz', '0013_observation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_region',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.region'),
        ),
    ]
