# Generated by Django 5.2.4 on 2025-08-17 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0001_initial'),
        ('quiz', '0013_observation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='observationtypeannotation',
            constraint=models.UniqueConstraint(fields=('user', 'observation'), name='unique_user_observation'),
        ),
    ]
